WARNING:tensorflow:From /home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING: Logging before flag parsing goes to stderr.
WARNING [tank-ProLiant-DL580-Gen9 192.168.1.128] Sep 13 16:31:38: Key:AtariDqn is registered, will replace with agent.
2023-09-13 16:31:42,022	INFO worker.py:1515 -- Started a local Ray instance. View the dashboard at [1m[32mhttp://127.0.0.1:8265 [39m[22m
2023-09-13 16:31:43,908	WARNING function_trainable.py:620 -- Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.
2023-09-13 16:31:43,973	WARNING trial_runner.py:1583 -- You are trying to access _search_alg interface of TrialRunner in TrialScheduler, which is being restricted. If you believe it is reasonable for your scheduler to access this TrialRunner API, please reach out to Ray team on GitHub. A more strict API access pattern would be enforced starting 1.12s.0
[2m[36m(train_xt pid=54600)[0m /home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py:166: ExperimentalWarning: BoTorchSampler is experimental (supported from v2.4.0). The interface can change in the future.
[2m[36m(train_xt pid=54600)[0m   n_startup_trials=1,
[2m[36m(train_xt pid=54600)[0m 2023-09-13 16:31:51,837	ERROR function_trainable.py:298 -- Runner Thread raised error.
[2m[36m(train_xt pid=54600)[0m Traceback (most recent call last):
[2m[36m(train_xt pid=54600)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 289, in run
[2m[36m(train_xt pid=54600)[0m     self._entrypoint()
[2m[36m(train_xt pid=54600)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 365, in entrypoint
[2m[36m(train_xt pid=54600)[0m     self._status_reporter.get_checkpoint(),
[2m[36m(train_xt pid=54600)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
[2m[36m(train_xt pid=54600)[0m     return method(self, *_args, **_kwargs)
[2m[36m(train_xt pid=54600)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 684, in _trainable_func
[2m[36m(train_xt pid=54600)[0m     output = fn()
[2m[36m(train_xt pid=54600)[0m   File "test_xt_with_tune.py", line 149, in train_xt
[2m[36m(train_xt pid=54600)[0m     best_param = find_max_th(yaml_file_path, n_trials, start_core, with_samper)
[2m[36m(train_xt pid=54600)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 184, in find_max_th
[2m[36m(train_xt pid=54600)[0m     print("study.best_params ===================== {}".format(study.best_params))
[2m[36m(train_xt pid=54600)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/study.py", line 117, in best_params
[2m[36m(train_xt pid=54600)[0m     return self.best_trial.params
[2m[36m(train_xt pid=54600)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/study.py", line 160, in best_trial
[2m[36m(train_xt pid=54600)[0m     return copy.deepcopy(self._storage.get_best_trial(self._study_id))
[2m[36m(train_xt pid=54600)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/storages/_cached_storage.py", line 182, in get_best_trial
[2m[36m(train_xt pid=54600)[0m     return self._backend.get_best_trial(study_id)
[2m[36m(train_xt pid=54600)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/storages/_rdb/storage.py", line 912, in get_best_trial
[2m[36m(train_xt pid=54600)[0m     trial = models.TrialModel.find_min_value_trial(study_id, 0, session)
[2m[36m(train_xt pid=54600)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/storages/_rdb/models.py", line 231, in find_min_value_trial
[2m[36m(train_xt pid=54600)[0m     raise ValueError(NOT_FOUND_MSG)
[2m[36m(train_xt pid=54600)[0m ValueError: Record does not exist.
[2m[36m(train_xt pid=54645)[0m /home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py:166: ExperimentalWarning: BoTorchSampler is experimental (supported from v2.4.0). The interface can change in the future.
[2m[36m(train_xt pid=54645)[0m   n_startup_trials=1,
[2m[36m(train_xt pid=54645)[0m WARNING:tensorflow:From /home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
[2m[36m(train_xt pid=54645)[0m Instructions for updating:
[2m[36m(train_xt pid=54645)[0m non-resource variables are not supported in the long term
[2m[36m(train_xt pid=54645)[0m WARNING: Logging before flag parsing goes to stderr.
[2m[36m(train_xt pid=54645)[0m WARNING [tank-ProLiant-DL580-Gen9 192.168.1.128] Sep 13 16:32:03: Key:AtariDqn is registered, will replace with agent.
[2m[36m(train_xt pid=54690)[0m /home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py:166: ExperimentalWarning: BoTorchSampler is experimental (supported from v2.4.0). The interface can change in the future.
[2m[36m(train_xt pid=54690)[0m   n_startup_trials=1,
[2m[36m(train_xt pid=54645)[0m INFO [tank-ProLiant-DL580-Gen9 192.168.1.128] Sep 13 16:32:04: 
[2m[36m(train_xt pid=54645)[0m **************************************************
[2m[36m(train_xt pid=54645)[0m  XT start work...
[2m[36m(train_xt pid=54645)[0m Namespace(config_file='/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/train_yaml/train_yaml_imopt/train_yaml_testImpalaCnnOpt_now_time_16945939194162855.yaml', save_to_s3=None, task='train', verbosity='info')
[2m[36m(train_xt pid=54645)[0m **************************************************
[2m[36m(train_xt pid=54645)[0m ERROR [tank-ProLiant-DL580-Gen9 192.168.1.128] Sep 13 16:32:04: module EnvPool not found: 'EnvPool'
[2m[36m(train_xt pid=54645)[0m ERROR [tank-ProLiant-DL580-Gen9 192.168.1.128] Sep 13 16:32:04: 'EnvPool'
[2m[36m(train_xt pid=54645)[0m Traceback (most recent call last):
[2m[36m(train_xt pid=54645)[0m   File "/root/multi_xt/mdqn/impala_compose-dqn_opt/xt/train.py", line 128, in start_train
[2m[36m(train_xt pid=54645)[0m     return _makeup_learner(config_info, data_url, verbosity)
[2m[36m(train_xt pid=54645)[0m   File "/root/multi_xt/mdqn/impala_compose-dqn_opt/xt/train.py", line 48, in _makeup_learner
[2m[36m(train_xt pid=54645)[0m     config_info = patch_alg_within_config(config_info.copy(), node_type="node_config")
[2m[36m(train_xt pid=54645)[0m   File "/root/multi_xt/mdqn/impala_compose-dqn_opt/xt/framework/learner.py", line 511, in patch_alg_within_config
[2m[36m(train_xt pid=54645)[0m     env = env_builder(**config["env_para"])
[2m[36m(train_xt pid=54645)[0m   File "/root/multi_xt/mdqn/impala_compose-dqn_opt/xt/environment/__init__.py", line 23, in env_builder
[2m[36m(train_xt pid=54645)[0m     return Registers.env[env_name](env_info, **kwargs)
[2m[36m(train_xt pid=54645)[0m   File "/root/multi_xt/mdqn/impala_compose-dqn_opt/zeus/common/util/register.py", line 56, in __getitem__
[2m[36m(train_xt pid=54645)[0m     raise exc
[2m[36m(train_xt pid=54645)[0m   File "/root/multi_xt/mdqn/impala_compose-dqn_opt/zeus/common/util/register.py", line 50, in __getitem__
[2m[36m(train_xt pid=54645)[0m     return self._dict[key]
[2m[36m(train_xt pid=54645)[0m KeyError: 'EnvPool'
[2m[36m(train_xt pid=54645)[0m sh: 1: kill: No such process
[2m[36m(train_xt pid=54645)[0m 
[2m[36m(train_xt pid=54645)[0m [W 2023-09-13 16:32:05,948] Trial 0 failed with parameters: {'env_pool_size': 4, 'env_pool_wait_nums': 3, 'infer_size': 3} because of the following error: FileNotFoundError(2, 'No such file or directory').
[2m[36m(train_xt pid=54645)[0m Traceback (most recent call last):
[2m[36m(train_xt pid=54645)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
[2m[36m(train_xt pid=54645)[0m     value_or_values = func(trial)
[2m[36m(train_xt pid=54645)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 182, in <lambda>
[2m[36m(train_xt pid=54645)[0m     study.optimize(lambda trial: fn(trial, start_core, with_samper), n_trials=n_trials)
[2m[36m(train_xt pid=54645)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 134, in fn
[2m[36m(train_xt pid=54645)[0m     step_per_second = get_throughput([filename])
[2m[36m(train_xt pid=54645)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 40, in get_throughput
[2m[36m(train_xt pid=54645)[0m     with open(file, "r") as f:
[2m[36m(train_xt pid=54645)[0m FileNotFoundError: [Errno 2] No such file or directory: '/tmp/16945939194162855'
[2m[36m(train_xt pid=54645)[0m [W 2023-09-13 16:32:05,948] Trial 0 failed with value None.
[2m[36m(train_xt pid=54645)[0m 2023-09-13 16:32:05,949	ERROR function_trainable.py:298 -- Runner Thread raised error.
[2m[36m(train_xt pid=54645)[0m Traceback (most recent call last):
[2m[36m(train_xt pid=54645)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 289, in run
[2m[36m(train_xt pid=54645)[0m     self._entrypoint()
[2m[36m(train_xt pid=54645)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 365, in entrypoint
[2m[36m(train_xt pid=54645)[0m     self._status_reporter.get_checkpoint(),
[2m[36m(train_xt pid=54645)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
[2m[36m(train_xt pid=54645)[0m     return method(self, *_args, **_kwargs)
[2m[36m(train_xt pid=54645)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 684, in _trainable_func
[2m[36m(train_xt pid=54645)[0m     output = fn()
[2m[36m(train_xt pid=54645)[0m   File "test_xt_with_tune.py", line 149, in train_xt
[2m[36m(train_xt pid=54645)[0m     best_param = find_max_th(yaml_file_path, n_trials, start_core, with_samper)
[2m[36m(train_xt pid=54645)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 182, in find_max_th
[2m[36m(train_xt pid=54645)[0m     study.optimize(lambda trial: fn(trial, start_core, with_samper), n_trials=n_trials)
[2m[36m(train_xt pid=54645)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/study.py", line 451, in optimize
[2m[36m(train_xt pid=54645)[0m     show_progress_bar=show_progress_bar,
[2m[36m(train_xt pid=54645)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 76, in _optimize
[2m[36m(train_xt pid=54645)[0m     progress_bar=progress_bar,
[2m[36m(train_xt pid=54645)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
[2m[36m(train_xt pid=54645)[0m     frozen_trial = _run_trial(study, func, catch)
[2m[36m(train_xt pid=54645)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
[2m[36m(train_xt pid=54645)[0m     raise func_err
[2m[36m(train_xt pid=54645)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
[2m[36m(train_xt pid=54645)[0m     value_or_values = func(trial)
[2m[36m(train_xt pid=54645)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 182, in <lambda>
[2m[36m(train_xt pid=54645)[0m     study.optimize(lambda trial: fn(trial, start_core, with_samper), n_trials=n_trials)
[2m[36m(train_xt pid=54645)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 134, in fn
[2m[36m(train_xt pid=54645)[0m     step_per_second = get_throughput([filename])
[2m[36m(train_xt pid=54645)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 40, in get_throughput
[2m[36m(train_xt pid=54645)[0m     with open(file, "r") as f:
[2m[36m(train_xt pid=54645)[0m FileNotFoundError: [Errno 2] No such file or directory: '/tmp/16945939194162855'
[2m[36m(train_xt pid=54690)[0m WARNING:tensorflow:From /home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
[2m[36m(train_xt pid=54690)[0m Instructions for updating:
[2m[36m(train_xt pid=54690)[0m non-resource variables are not supported in the long term
[2m[36m(train_xt pid=54690)[0m WARNING: Logging before flag parsing goes to stderr.
[2m[36m(train_xt pid=54690)[0m WARNING [tank-ProLiant-DL580-Gen9 192.168.1.128] Sep 13 16:32:10: Key:AtariDqn is registered, will replace with agent.
[2m[36m(train_xt pid=54690)[0m INFO [tank-ProLiant-DL580-Gen9 192.168.1.128] Sep 13 16:32:11: 
[2m[36m(train_xt pid=54690)[0m **************************************************
[2m[36m(train_xt pid=54690)[0m  XT start work...
[2m[36m(train_xt pid=54690)[0m Namespace(config_file='/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/train_yaml/train_yaml_imopt/train_yaml_testImpalaCnnOpt_now_time_16945939258604639.yaml', save_to_s3=None, task='train', verbosity='info')
[2m[36m(train_xt pid=54690)[0m **************************************************
[2m[36m(train_xt pid=54690)[0m ERROR [tank-ProLiant-DL580-Gen9 192.168.1.128] Sep 13 16:32:11: module EnvPool not found: 'EnvPool'
[2m[36m(train_xt pid=54690)[0m ERROR [tank-ProLiant-DL580-Gen9 192.168.1.128] Sep 13 16:32:11: 'EnvPool'
[2m[36m(train_xt pid=54690)[0m Traceback (most recent call last):
[2m[36m(train_xt pid=54690)[0m   File "/root/multi_xt/mdqn/impala_compose-dqn_opt/xt/train.py", line 128, in start_train
[2m[36m(train_xt pid=54690)[0m     return _makeup_learner(config_info, data_url, verbosity)
[2m[36m(train_xt pid=54690)[0m   File "/root/multi_xt/mdqn/impala_compose-dqn_opt/xt/train.py", line 48, in _makeup_learner
[2m[36m(train_xt pid=54690)[0m     config_info = patch_alg_within_config(config_info.copy(), node_type="node_config")
[2m[36m(train_xt pid=54690)[0m   File "/root/multi_xt/mdqn/impala_compose-dqn_opt/xt/framework/learner.py", line 511, in patch_alg_within_config
[2m[36m(train_xt pid=54690)[0m     env = env_builder(**config["env_para"])
[2m[36m(train_xt pid=54690)[0m   File "/root/multi_xt/mdqn/impala_compose-dqn_opt/xt/environment/__init__.py", line 23, in env_builder
[2m[36m(train_xt pid=54690)[0m     return Registers.env[env_name](env_info, **kwargs)
[2m[36m(train_xt pid=54690)[0m   File "/root/multi_xt/mdqn/impala_compose-dqn_opt/zeus/common/util/register.py", line 56, in __getitem__
[2m[36m(train_xt pid=54690)[0m     raise exc
[2m[36m(train_xt pid=54690)[0m   File "/root/multi_xt/mdqn/impala_compose-dqn_opt/zeus/common/util/register.py", line 50, in __getitem__
[2m[36m(train_xt pid=54690)[0m     return self._dict[key]
[2m[36m(train_xt pid=54690)[0m KeyError: 'EnvPool'
2023-09-13 16:32:12,327	ERROR trial_runner.py:987 -- Trial train_xt_f8584_00001: Error processing event.
ray.exceptions.RayTaskError(FileNotFoundError): [36mray::ImplicitFunc.train()[39m (pid=54645, ip=192.168.1.128, repr=train_xt)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/trainable.py", line 349, in train
    result = self.step()
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 417, in step
    self._report_thread_runner_error(block=True)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 589, in _report_thread_runner_error
    raise e
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 289, in run
    self._entrypoint()
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 365, in entrypoint
    self._status_reporter.get_checkpoint(),
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 684, in _trainable_func
    output = fn()
  File "test_xt_with_tune.py", line 149, in train_xt
    best_param = find_max_th(yaml_file_path, n_trials, start_core, with_samper)
  File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 182, in find_max_th
    study.optimize(lambda trial: fn(trial, start_core, with_samper), n_trials=n_trials)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/study.py", line 451, in optimize
    show_progress_bar=show_progress_bar,
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 76, in _optimize
    progress_bar=progress_bar,
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 182, in <lambda>
    study.optimize(lambda trial: fn(trial, start_core, with_samper), n_trials=n_trials)
  File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 134, in fn
    step_per_second = get_throughput([filename])
  File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 40, in get_throughput
    with open(file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/16945939194162855'
2023-09-13 16:32:12,349	ERROR trial_runner.py:987 -- Trial train_xt_f8584_00000: Error processing event.
ray.exceptions.RayTaskError(ValueError): [36mray::ImplicitFunc.train()[39m (pid=54600, ip=192.168.1.128, repr=train_xt)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/trainable.py", line 349, in train
    result = self.step()
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 417, in step
    self._report_thread_runner_error(block=True)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 589, in _report_thread_runner_error
    raise e
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 289, in run
    self._entrypoint()
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 365, in entrypoint
    self._status_reporter.get_checkpoint(),
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 684, in _trainable_func
    output = fn()
  File "test_xt_with_tune.py", line 149, in train_xt
    best_param = find_max_th(yaml_file_path, n_trials, start_core, with_samper)
  File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 184, in find_max_th
    print("study.best_params ===================== {}".format(study.best_params))
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/study.py", line 117, in best_params
    return self.best_trial.params
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/study.py", line 160, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/storages/_cached_storage.py", line 182, in get_best_trial
    return self._backend.get_best_trial(study_id)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/storages/_rdb/storage.py", line 912, in get_best_trial
    trial = models.TrialModel.find_min_value_trial(study_id, 0, session)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/storages/_rdb/models.py", line 231, in find_min_value_trial
    raise ValueError(NOT_FOUND_MSG)
ValueError: Record does not exist.
[2m[36m(train_xt pid=54690)[0m sh: 1: kill: No such process
[2m[36m(train_xt pid=54690)[0m 
[2m[36m(train_xt pid=54690)[0m [W 2023-09-13 16:32:12,604] Trial 1 failed with parameters: {'env_pool_size': 3, 'env_pool_wait_nums': 2, 'infer_size': 2} because of the following error: FileNotFoundError(2, 'No such file or directory').
[2m[36m(train_xt pid=54690)[0m Traceback (most recent call last):
[2m[36m(train_xt pid=54690)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
[2m[36m(train_xt pid=54690)[0m     value_or_values = func(trial)
[2m[36m(train_xt pid=54690)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 182, in <lambda>
[2m[36m(train_xt pid=54690)[0m     study.optimize(lambda trial: fn(trial, start_core, with_samper), n_trials=n_trials)
[2m[36m(train_xt pid=54690)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 134, in fn
[2m[36m(train_xt pid=54690)[0m     step_per_second = get_throughput([filename])
[2m[36m(train_xt pid=54690)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 40, in get_throughput
[2m[36m(train_xt pid=54690)[0m     with open(file, "r") as f:
[2m[36m(train_xt pid=54690)[0m FileNotFoundError: [Errno 2] No such file or directory: '/tmp/16945939258604639'
[2m[36m(train_xt pid=54690)[0m [W 2023-09-13 16:32:12,605] Trial 1 failed with value None.
[2m[36m(train_xt pid=54690)[0m 2023-09-13 16:32:12,605	ERROR function_trainable.py:298 -- Runner Thread raised error.
[2m[36m(train_xt pid=54690)[0m Traceback (most recent call last):
[2m[36m(train_xt pid=54690)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 289, in run
[2m[36m(train_xt pid=54690)[0m     self._entrypoint()
[2m[36m(train_xt pid=54690)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 365, in entrypoint
[2m[36m(train_xt pid=54690)[0m     self._status_reporter.get_checkpoint(),
[2m[36m(train_xt pid=54690)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
[2m[36m(train_xt pid=54690)[0m     return method(self, *_args, **_kwargs)
[2m[36m(train_xt pid=54690)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 684, in _trainable_func
[2m[36m(train_xt pid=54690)[0m     output = fn()
[2m[36m(train_xt pid=54690)[0m   File "test_xt_with_tune.py", line 149, in train_xt
[2m[36m(train_xt pid=54690)[0m     best_param = find_max_th(yaml_file_path, n_trials, start_core, with_samper)
[2m[36m(train_xt pid=54690)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 182, in find_max_th
[2m[36m(train_xt pid=54690)[0m     study.optimize(lambda trial: fn(trial, start_core, with_samper), n_trials=n_trials)
[2m[36m(train_xt pid=54690)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/study.py", line 451, in optimize
[2m[36m(train_xt pid=54690)[0m     show_progress_bar=show_progress_bar,
[2m[36m(train_xt pid=54690)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 76, in _optimize
[2m[36m(train_xt pid=54690)[0m     progress_bar=progress_bar,
[2m[36m(train_xt pid=54690)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
[2m[36m(train_xt pid=54690)[0m     frozen_trial = _run_trial(study, func, catch)
[2m[36m(train_xt pid=54690)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
[2m[36m(train_xt pid=54690)[0m     raise func_err
[2m[36m(train_xt pid=54690)[0m   File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
[2m[36m(train_xt pid=54690)[0m     value_or_values = func(trial)
[2m[36m(train_xt pid=54690)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 182, in <lambda>
[2m[36m(train_xt pid=54690)[0m     study.optimize(lambda trial: fn(trial, start_core, with_samper), n_trials=n_trials)
[2m[36m(train_xt pid=54690)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 134, in fn
[2m[36m(train_xt pid=54690)[0m     step_per_second = get_throughput([filename])
[2m[36m(train_xt pid=54690)[0m   File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 40, in get_throughput
[2m[36m(train_xt pid=54690)[0m     with open(file, "r") as f:
[2m[36m(train_xt pid=54690)[0m FileNotFoundError: [Errno 2] No such file or directory: '/tmp/16945939258604639'
[2m[36m(train_xt pid=54784)[0m /home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py:166: ExperimentalWarning: BoTorchSampler is experimental (supported from v2.4.0). The interface can change in the future.
[2m[36m(train_xt pid=54784)[0m   n_startup_trials=1,
2023-09-13 16:32:12,756	ERROR trial_runner.py:987 -- Trial train_xt_f8584_00002: Error processing event.
ray.exceptions.RayTaskError(FileNotFoundError): [36mray::ImplicitFunc.train()[39m (pid=54690, ip=192.168.1.128, repr=train_xt)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/trainable.py", line 349, in train
    result = self.step()
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 417, in step
    self._report_thread_runner_error(block=True)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 589, in _report_thread_runner_error
    raise e
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 289, in run
    self._entrypoint()
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 365, in entrypoint
    self._status_reporter.get_checkpoint(),
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py", line 684, in _trainable_func
    output = fn()
  File "test_xt_with_tune.py", line 149, in train_xt
    best_param = find_max_th(yaml_file_path, n_trials, start_core, with_samper)
  File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 182, in find_max_th
    study.optimize(lambda trial: fn(trial, start_core, with_samper), n_trials=n_trials)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/study.py", line 451, in optimize
    show_progress_bar=show_progress_bar,
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 76, in _optimize
    progress_bar=progress_bar,
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 182, in <lambda>
    study.optimize(lambda trial: fn(trial, start_core, with_samper), n_trials=n_trials)
  File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 134, in fn
    step_per_second = get_throughput([filename])
  File "/home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/test_resources/test_optuna_bys.py", line 40, in get_throughput
    with open(file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/16945939258604639'
2023-09-13 16:32:13,765	WARNING tune.py:687 -- Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. 
tune_system ================== True
with_samper ================== True
== Status ==
Current time: 2023-09-13 16:31:51 (running for 00:00:07.12)
Memory usage on this node: 38.6/251.8 GiB
PopulationBasedTraining: 0 checkpoints, 0 perturbs
Resources requested: 10.0/80 CPUs, 0.4/3 GPUs, 0.0/144.71 GiB heap, 0.0/66.01 GiB objects (0.0/1.0 accelerator_type:X)
Result logdir: /tmp/ray_results/pb2_test4
Number of trials: 4/4 (3 PENDING, 1 RUNNING)


[2m[36m(train_xt pid=54600)[0m {'lr': 0.004620769751785016, 'checkpoint_interval': 1}
[2m[36m(train_xt pid=54600)[0m trail id ================= f8584_00000
== Status ==
Current time: 2023-09-13 16:31:57 (running for 00:00:13.64)
Memory usage on this node: 38.8/251.8 GiB
PopulationBasedTraining: 0 checkpoints, 0 perturbs
Resources requested: 20.0/80 CPUs, 0.8/3 GPUs, 0.0/144.71 GiB heap, 0.0/66.01 GiB objects (0.0/1.0 accelerator_type:X)
Result logdir: /tmp/ray_results/pb2_test4
Number of trials: 4/4 (2 PENDING, 2 RUNNING)


[2m[36m(train_xt pid=54645)[0m {'lr': 0.004581602113825932, 'checkpoint_interval': 1}
[2m[36m(train_xt pid=54645)[0m trail id ================= f8584_00001
[2m[36m(train_xt pid=54645)[0m =======================env_pool_size======================4
[2m[36m(train_xt pid=54645)[0m =======================env_pool_wait_nums======================3
[2m[36m(train_xt pid=54645)[0m get max throughput start_core============================= True
[2m[36m(train_xt pid=54645)[0m yaml_filepath ================== /home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/train_yaml/train_yaml_imopt/train_yaml_testImpalaCnnOpt_now_time_16945939194162855.yaml
[2m[36m(train_xt pid=54645)[0m run_log ======================== /tmp/test_opt_bys16945939194162855.log
== Status ==
Current time: 2023-09-13 16:32:04 (running for 00:00:20.11)
Memory usage on this node: 39.3/251.8 GiB
PopulationBasedTraining: 0 checkpoints, 0 perturbs
Resources requested: 30.0/80 CPUs, 1.2000000000000002/3 GPUs, 0.0/144.71 GiB heap, 0.0/66.01 GiB objects (0.0/1.0 accelerator_type:X)
Result logdir: /tmp/ray_results/pb2_test4
Number of trials: 4/4 (1 PENDING, 3 RUNNING)


[2m[36m(train_xt pid=54690)[0m {'lr': 0.0022931178041364613, 'checkpoint_interval': 1}
[2m[36m(train_xt pid=54690)[0m trail id ================= f8584_00002
[2m[36m(train_xt pid=54645)[0m good
[2m[36m(train_xt pid=54645)[0m log filename ================== /tmp/16945939194162855
[2m[36m(train_xt pid=54690)[0m =======================env_pool_size======================3
[2m[36m(train_xt pid=54690)[0m =======================env_pool_wait_nums======================2
[2m[36m(train_xt pid=54690)[0m get max throughput start_core============================= True
[2m[36m(train_xt pid=54690)[0m yaml_filepath ================== /home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/train_yaml/train_yaml_imopt/train_yaml_testImpalaCnnOpt_now_time_16945939258604639.yaml
[2m[36m(train_xt pid=54690)[0m run_log ======================== /tmp/test_opt_bys16945939258604639.log
== Status ==
Current time: 2023-09-13 16:32:12 (running for 00:00:28.36)
Memory usage on this node: 39.5/251.8 GiB
PopulationBasedTraining: 0 checkpoints, 0 perturbs
Resources requested: 40.0/80 CPUs, 1.6/3 GPUs, 0.0/144.71 GiB heap, 0.0/66.01 GiB objects (0.0/1.0 accelerator_type:X)
Result logdir: /tmp/ray_results/pb2_test4
Number of trials: 4/4 (4 RUNNING)


== Status ==
Current time: 2023-09-13 16:32:12 (running for 00:00:28.37)
Memory usage on this node: 39.5/251.8 GiB
PopulationBasedTraining: 0 checkpoints, 0 perturbs
Resources requested: 30.0/80 CPUs, 1.2000000000000002/3 GPUs, 0.0/144.71 GiB heap, 0.0/66.01 GiB objects (0.0/1.0 accelerator_type:X)
Result logdir: /tmp/ray_results/pb2_test4
Number of trials: 4/4 (1 ERROR, 3 RUNNING)
Number of errored trials: 1
+----------------------+--------------+-------------------------------------------------------------------------------------------+
| Trial name           |   # failures | error file                                                                                |
|----------------------+--------------+-------------------------------------------------------------------------------------------|
| train_xt_f8584_00001 |            1 | /tmp/ray_results/pb2_test4/train_xt_f8584_00001_1_lr=0.0046_2023-09-13_16-31-51/error.txt |
+----------------------+--------------+-------------------------------------------------------------------------------------------+

[2m[36m(train_xt pid=54784)[0m {'lr': 0.002135467051243755, 'checkpoint_interval': 1}
[2m[36m(train_xt pid=54784)[0m trail id ================= f8584_00003
[2m[36m(train_xt pid=54690)[0m good
[2m[36m(train_xt pid=54690)[0m log filename ================== /tmp/16945939258604639
[2m[36m(train_xt pid=54784)[0m =======================env_pool_size======================2
[2m[36m(train_xt pid=54784)[0m =======================env_pool_wait_nums======================2
[2m[36m(train_xt pid=54784)[0m get max throughput start_core============================= True
[2m[36m(train_xt pid=54784)[0m yaml_filepath ================== /home/xys/xingtian-test/xingtian-project-pipeline_impala/tests/avan/train_yaml/train_yaml_imopt/train_yaml_testImpalaCnnOpt_now_time_1694593934134383.yaml
[2m[36m(train_xt pid=54784)[0m run_log ======================== /tmp/test_opt_bys1694593934134383.log
Traceback (most recent call last):
  File "test_xt_with_tune.py", line 262, in <module>
    results_grid = tuner.fit()
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/tuner.py", line 234, in fit
    return self._local_tuner.fit()
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/impl/tuner_internal.py", line 283, in fit
    analysis = self._fit_internal(trainable, param_space)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/impl/tuner_internal.py", line 381, in _fit_internal
    **args,
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/tune.py", line 722, in run
    runner.step()
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/execution/trial_runner.py", line 879, in step
    self._wait_and_handle_event(next_trial)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/execution/trial_runner.py", line 823, in _wait_and_handle_event
    self._live_trials, next_trial is not None
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/tune/execution/ray_trial_executor.py", line 953, in get_next_executor_event
    futures_to_wait, num_returns=1, timeout=self._get_next_event_wait
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/_private/worker.py", line 2471, in wait
    fetch_local,
  File "python/ray/_raylet.pyx", line 1414, in ray._raylet.CoreWorker.wait
  File "python/ray/_raylet.pyx", line 173, in ray._raylet.check_status
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/tank/miniconda3/envs/openmmlab/lib/python3.7/site-packages/ray/_private/worker.py", line 1580, in shutdown
    time.sleep(0.5)
KeyboardInterrupt
